version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: banco_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: banco_dio
      MYSQL_USER: banco_user
      MYSQL_PASSWORD: banco_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "banco_user", "-pbanco_pass"]
      timeout: 30s
      retries: 15
      interval: 10s
      start_period: 30s

  backend:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://banco_user:banco_pass@mysql:3306/banco_dio
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - banco_network
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - banco_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  banco_network:
    driver: bridge